from repositories.appointment_repository import AppointmentRepository
from models.appointment import Appointment

from PyQt6.QtCore import QObject, pyqtSignal

class AppointmentService(QObject):
    changed = pyqtSignal()

    def __init__(self):
        super().__init__()
        self.repo = AppointmentRepository()

    def get_appointment_by_code(
        self,
        code: str
    ) -> Appointment | None:

        return self.repo.get_by_code(code)

    def create_appointment(
        self,
        appt_date: str,
        appt_time: str,
        purpose: str,
        clinic_name: str,
        status: str,
        patient_id: int
    ) -> Appointment:

        # appointment_id and appointment_code
        # are generated by the repository
        appointment = Appointment(
            appointment_id=None,
            appointment_code=None,
            appt_date=appt_date,
            appt_time=appt_time,
            purpose=purpose,
            clinic_name=clinic_name,
            status=status,
            patient_id=patient_id
        )

        self.repo.create(appointment)
        self.changed.emit()
        return appointment

    def get_appointment_by_id(
        self,
        appointment_id: int
    ) -> Appointment | None:

        return self.repo.get_by_id(appointment_id)

    def get_all_appointments(self) -> list[Appointment]:

        return self.repo.get_all()

    def get_appointments_by_patient_id(
        self,
        patient_id: int
    ) -> list[Appointment]:

        return self.repo.get_by_patient_id(patient_id)

    def search_appointments(
        self,
        keyword: str
    ) -> list[Appointment]:

        return self.repo.search(keyword)

    def update_appointment(
        self,
        appointment_id: int,
        appt_date: str,
        appt_time: str,
        purpose: str,
        clinic_name: str,
        status: str,
        patient_id: int
    ) -> Appointment:

        appointment = Appointment(
            appointment_id=appointment_id,
            appointment_code=None,  # ignored on update
            appt_date=appt_date,
            appt_time=appt_time,
            purpose=purpose,
            clinic_name=clinic_name,
            status=status,
            patient_id=patient_id
        )

        self.repo.update(appointment)
        self.changed.emit()
        return appointment

    def delete_appointment(
        self,
        appointment_id: int
    ):

        self.repo.delete(appointment_id)
        self.changed.emit()
