from repositories.patient_repository import PatientRepository
from models.patient import Patient


class PatientService:
    def __init__(self):
        self.repo = PatientRepository()

    def get_patient_by_code(
        self,
        patient_code: str
    ) -> Patient | None:

        return self.repo.get_by_code(
            patient_code
        )

    def register_patient(
        self,
        first_name: str,
        last_name: str,
        birthdate: str,
        sex: str
    ) -> Patient:

        # patient_id and patient_code are generated by the repository
        patient = Patient(
            patient_id=None,
            patient_code=None,
            first_name=first_name,
            last_name=last_name,
            birthdate=birthdate,
            sex=sex
        )

        return self.repo.create(patient)

    def get_patient_by_id(
        self,
        patient_id: int
    ) -> Patient | None:

        return self.repo.get_by_id(patient_id)

    def get_all_patients(self) -> list[Patient]:

        return self.repo.get_all()

    def search_patients(
        self,
        keyword: str
    ) -> list[Patient]:

        return self.repo.search(keyword)

    def update_patient(
        self,
        patient_id: int,
        first_name: str,
        last_name: str,
        birthdate: str,
        sex: str
    ):

        patient = Patient(
            patient_id=patient_id,
            patient_code=None,  # ignored on update
            first_name=first_name,
            last_name=last_name,
            birthdate=birthdate,
            sex=sex
        )

        return self.repo.update(patient)

    def delete_patient(
        self,
        patient_id: int
    ):

        self.repo.delete(patient_id)
