from repositories.visit_record_repository import VisitRecordRepository
from models.visit_record import VisitRecord
from PyQt6.QtCore import QObject, pyqtSignal


class VisitRecordService(QObject):
    changed = pyqtSignal()

    def __init__(self):
        super().__init__()
        self.repo = VisitRecordRepository()

    def get_record_by_code(
        self,
        code: str
    ) -> VisitRecord | None:

        return self.repo.get_by_code(code)

    def create_visit_record(
        self,
        visit_date: str,
        weight_kg: float | None,
        blood_pressure: str | None,
        patient_id: int
    ) -> VisitRecord:

        # record_id and record_code are generated by the repository
        visit_record = VisitRecord(
            record_id=None,
            record_code=None,
            visit_date=visit_date,
            weight_kg=weight_kg,
            blood_pressure=blood_pressure,
            patient_id=patient_id
        )

        self.repo.create(visit_record)
        self.changed.emit()
        return visit_record

    def get_visit_record_by_id(
        self,
        record_id: int
    ) -> VisitRecord | None:

        return self.repo.get_by_id(record_id)

    def get_all_visit_records(self) -> list[VisitRecord]:

        return self.repo.get_all()

    def get_visit_records_by_patient_id(
        self,
        patient_id: int
    ) -> list[VisitRecord]:

        return self.repo.get_by_patient_id(patient_id)

    def search_visit_records(
        self,
        keyword: str
    ) -> list[VisitRecord]:

        return self.repo.search(keyword)

    def update_visit_record(
        self,
        record_id: int,
        visit_date: str,
        weight_kg: float | None,
        blood_pressure: str | None,
        patient_id: int
    ):

        visit_record = VisitRecord(
            record_id=record_id,
            record_code=None,  # ignored on update
            visit_date=visit_date,
            weight_kg=weight_kg,
            blood_pressure=blood_pressure,
            patient_id=patient_id
        )

        self.repo.update(visit_record)
        self.changed.emit()
        return visit_record

    def delete_visit_record(
        self,
        record_id: int
    ):

        self.repo.delete(record_id)
        self.changed.emit()
